# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5b377675c86f64f90dac3dc1066c81fa2318034d13b21f6305b62d057c7b25838e355e613761ef1092b6e8ce69b282cbf17b245c6d64891d032878459121b6b9

test:
  secret_key_base: da184e097427490cadae915625587d9636fbe7ea434856884f97db77ede6579eaf64ff0f949f0dac18cb8154d59ab7bda801346afd8a7c7670332f7b16f355c7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
